spring:
  application:
    name: ms-producto-service

  profiles:
    active: development

  config:
    import: optional:configserver:http://david:61321351@localhost:7070

  web:
    resources:
      static-locations: file:uploads/
